apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  namespace: {{ .Values.namespace }}
  name: {{ include "server-api.fullname" . }}
  labels:
    {{- include "server-api.labels" . | nindent 4 }}
spec:
  encryptedData:
    dbPassword: {{ .Values.db.dbPassword }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: {{ include "server-api.fullname" . }}
      namespace: {{ .Values.namespace }}

