apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-ebs" .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
