apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-ebs" .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
