apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-efs" .Chart.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
