apiVersion: v1
kind: Service
metadata:
  name: {{ include "server-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "server-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
      protocol: TCP
      name: {{ include "server-api.fullname" . }}
  selector:
    {{- include "server-api.selectorLabels" . | nindent 4 }}
