apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mixer-nginx.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      access_log /dev/stdout;
      server {
          listen       80;
          server_name  _;
          location /upload {
            alias /src/dev/upload-output;
          }
      }
    }