apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mixer-nginx.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
