apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beam-efs-pvc
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
