grafana.ini:
  server:
    domain: monitoring.beam.to
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
ingress:
  enabled: false
  hosts:
    - "monitoring.beam.to"
  path: "/grafana"

nodeSelector:
  kubernetes.io/os: ${operating_system}

persistence:
  type: pvc
  enabled: true
  storageClassName: efs-sc
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
  inMemory:
    enabled: false
    
initChownData:
  enabled: false
