nodeSelector:
  kubernetes.io/os: ${operating_system}

persistence:
  type: pvc
  enabled: true
  storageClassName: efs-sc
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
  inMemory:
    enabled: false
    
initChownData:
  enabled: false

securityContext:
  fsGroup: 472
  runAsUser: 472
  runAsGroup: 472
serviceAccount:
  name: grafana
  annotations:
    eks.amazonaws.com/role-arn: aws-role