server:
  retention: 1h

  resources:
    requests:
      cpu: 500m
      memory: 512Mi

  global:
    scrape_interval: 15s

  nodeSelector:
    kubernetes.io/os: ${operating_system}

alertmanager:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
  metricLabelsAllowlist:
    - pods=[*]
    - nodes=[*]
    - deployments=[*]

nodeExporter:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

pushgateway:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

nodeSelector:
  kubernetes.io/os: ${operating_system}
